# Common parameters for both local and global costmaps

# Robot configuration
# robot_radius: 0.2  # Adjust based on your robot size
footprint: [[-0.10, -0.075], [-0.10, 0.075], [0.10, 0.075], [0.10, -0.075]]


# Inflation parameters
inflation_radius: 0.3
cost_scaling_factor: 10.0

# Obstacle layer
obstacle_layer:
  enabled: true
  max_obstacle_height: 0.6
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  unknown_threshold: 15
  mark_threshold: 0
  combination_method: 1
  track_unknown_space: false
  obstacle_range: 2.5
  raytrace_range: 3.0
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  publish_voxel_map: false
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    topic: /scan
    max_obstacle_height: 0.4
    clearing: true
    marking: true
    data_type: "LaserScan"
    raytrace_max_range: 3.0
    raytrace_min_range: 0.0
    obstacle_max_range: 2.5
    obstacle_min_range: 0.0

# Inflation layer
inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.3